"""empty message

Revision ID: 27a968ec3883
Revises: 
Create Date: 2023-04-05 23:42:08.029504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a968ec3883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('user_vk_id', sa.Integer(), nullable=False),
    sa.Column('stats', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_vk_id')
    )
    op.create_index(op.f('ix_stats_user_vk_id'), 'stats', ['user_vk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_user_vk_id'), table_name='stats')
    op.drop_table('stats')
    # ### end Alembic commands ###
